### ISSUE TITLE
React Web

### ISSUE THREAD

**Issue by mariohmol** [mongodb-js/compass-aggregations#103]
Hi!

Is there any way to run this project as React Web? So we can use this interface to be a web based  app?

bests

**Comment by lrlna** [comment]
hiya @mariohmol ! Sorry for the late reply. You should be able to configure it to work in the browser. There is [an example in the readme](https://github.com/mongodb-js/compass-aggregations#browser) how to set it up.

**Comment by mariohmol** [comment]
thank you!
